<?php
$preservation_slider_sc = preservation_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $preservation_slider_sc ) && strpos( $preservation_slider_sc, '[' ) !== false && strpos( $preservation_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider
		<?php
		if ( preservation_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
	">
	<?php
		// Add anchor
		$preservation_anchor_icon = preservation_get_theme_option( 'front_page_title_anchor_icon' );
		$preservation_anchor_text = preservation_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $preservation_anchor_icon ) || ! empty( $preservation_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $preservation_anchor_icon ) ? ' icon="' . esc_attr( $preservation_anchor_icon ) . '"' : '' )
									. ( ! empty( $preservation_anchor_text ) ? ' title="' . esc_attr( $preservation_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $preservation_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$preservation_scheme = preservation_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $preservation_scheme ) && ! preservation_is_inherit( $preservation_scheme ) ) {
			echo ' scheme_' . esc_attr( $preservation_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( preservation_get_theme_option( 'front_page_title_paddings' ) );
		if ( preservation_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
		"
		<?php
		$preservation_css      = '';
		$preservation_bg_image = preservation_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $preservation_bg_image ) ) {
			$preservation_css .= 'background-image: url(' . esc_url( preservation_get_attachment_url( $preservation_bg_image ) ) . ');';
		}
		if ( ! empty( $preservation_css ) ) {
			echo ' style="' . esc_attr( $preservation_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$preservation_anchor_icon = preservation_get_theme_option( 'front_page_title_anchor_icon' );
		$preservation_anchor_text = preservation_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $preservation_anchor_icon ) || ! empty( $preservation_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $preservation_anchor_icon ) ? ' icon="' . esc_attr( $preservation_anchor_icon ) . '"' : '' )
									. ( ! empty( $preservation_anchor_text ) ? ' title="' . esc_attr( $preservation_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( preservation_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' preservation-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$preservation_css      = '';
			$preservation_bg_mask  = preservation_get_theme_option( 'front_page_title_bg_mask' );
			$preservation_bg_color_type = preservation_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $preservation_bg_color_type ) {
				$preservation_bg_color = preservation_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $preservation_bg_color_type ) {
				$preservation_bg_color = preservation_get_scheme_color( 'bg_color', $preservation_scheme );
			} else {
				$preservation_bg_color = '';
			}
			if ( ! empty( $preservation_bg_color ) && $preservation_bg_mask > 0 ) {
				$preservation_css .= 'background-color: ' . esc_attr(
					1 == $preservation_bg_mask ? $preservation_bg_color : preservation_hex2rgba( $preservation_bg_color, $preservation_bg_mask )
				) . ';';
			}
			if ( ! empty( $preservation_css ) ) {
				echo ' style="' . esc_attr( $preservation_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$preservation_caption = preservation_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $preservation_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $preservation_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $preservation_caption, 'preservation_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$preservation_description = preservation_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $preservation_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $preservation_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $preservation_description ), 'preservation_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( preservation_get_theme_option( 'front_page_title_button1_link' ) != '' || preservation_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						preservation_show_layout( preservation_customizer_partial_refresh_front_page_title_button1_link() );
						preservation_show_layout( preservation_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
